version: 2.1

orbs:
  php: circleci/php@1

workflows:
  build:
    jobs:
      - php/test:
          name: php-<< matrix.version >>
          matrix:
            parameters:
              version: ["7.4", "5.6"]
